### ISSUE TITLE
Two different methods of showing provenance in Siegfried/Wikidata demo: we need to resolve this to one

### ISSUE THREAD

**Issue by ross-spencer** [ross-spencer/WikiDP-Issues#4]
**Description of problem**

In the [Siegfried demo](https://github.com/richardlehane/siegfried/releases/tag/v1.9-demo-1) I created two different ways of showing provenance from Wikidata. The differences between the two options are shown below. This issue can serve as a conversation prompt for deciding which might be best. The second option might simply not work well for Siegfried, or describe the output clearly enough so it might be a moot point.

* **Option 1:**

```yaml
filename : 'wikidata-skeleton-suite-demo-v1.0/Q939636.cdr'
filesize : 4
modified : 2020-06-21T22:19:01-04:00
errors   : 
matches  :
  - ns      : 'wikidata'
    id      : 'Q939636'
    format  : 'CorelDRAW Document'
    URI     : 'http://www.wikidata.org/entity/Q939636'
    mime    : 
    basis   : 'extension match cdr; byte match at 0, 4 (Gary Kessler''s File Signature Table (source date: 2017-08-08))'
    warning : 
---
filename : 'wikidata-skeleton-suite-demo-v1.0/Q942350.qt'
filesize : 12
modified : 2020-06-21T22:19:01-04:00
errors   : 
matches  :
  - ns      : 'wikidata'
    id      : 'Q942350'
    format  : 'QuickTime File Format'
    URI     : 'http://www.wikidata.org/entity/Q942350'
    mime    : 'video/quicktime'
    basis   : 'extension match qt; byte match at 0, 12 (signature 1/9) (Gary Kessler''s File Signature Table (source date: 2017-08-08)); byte match at 4, 8 (signature 5/9) (PRONOM (Official (x-fmt/384)))'
    warning : 
```

* **Option 2:** 

```yaml
filename : 'wikidata-skeleton-suite-demo-v1.0/Q939636.cdr'
filesize : 4
modified : 2020-06-21T22:19:01-04:00
errors   : 
matches  :
  - ns      : 'wikidata'
    id      : 'Q939636'
    format  : 'CorelDRAW Document'
    URI     : 'http://www.wikidata.org/entity/Q939636'
    mime    : 
    basis   : 'extension match cdr; byte match at 0, 4'
    source  : 'Gary Kessler''s File Signature Table (source date: 2017-08-08)'
    warning : 
---
filename : 'wikidata-skeleton-suite-demo-v1.0/Q942350.qt'
filesize : 12
modified : 2020-06-21T22:19:01-04:00
errors   : 
matches  :
  - ns      : 'wikidata'
    id      : 'Q942350'
    format  : 'QuickTime File Format'
    URI     : 'http://www.wikidata.org/entity/Q942350'
    mime    : 'video/quicktime'
    basis   : 'extension match qt; byte match at 0, 12 (signature 1/9); byte match at 4, 8 (signature 5/9)'
    source  : 'Gary Kessler''s File Signature Table (source date: 2017-08-08) PRONOM (Official (x-fmt/384))'
    warning :
```
